export const HOME_ROUTE = '/'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const CREATE_ROUTE = '/note/create'
export const EDIT_ROUTE = '/note/edit'
export const SEARCH_ROUTE = '/search'